name: 'Branch Guardian'
description: 'Create and/or delete branch protection rules based on a supplied branch pattern.'
author: 'Infamous Riddles'
branding:
  icon: 'git-branch'  
  color: 'blue'
inputs:
  BASE-BRANCH-PATTERN:
    description: 'The pattern of the base branch'
  PERSONAL-ACCESS-TOKEN:
    description: 'Personal access token to read branch protection rules'
  RULES-LIMIT:
    description: 'The number of branch protection rules to check in order to find and delete'
    default: 100
  REQUIRED-NUMBER-OF-REVIEWERS:
    description: 'The number of required reviewers when creating a branch protection rule'
    default: 1
  REQUIRED-STATUS-CHECKS:
    description: 'The status check that need to be successful before a PR can be merged.'
  REQUIRE-REVIEW-FROM-CODEOWNERS:
    description: 'Set to true if you need to require an approved review in pull requests including files with a designated code owner.'
    default: 'false'
  DISMISS-STALE-PR-APPROVALS-ON-NEW-COMMITS:
    description: 'Set to true if you need new reviewable commits pushed to a matching branch to dismiss pull request review approvals.'
    default: 'false'
  REQUIRE-LINEAR-HISTORY:
    description: 'Set to true if you need linear history on your Pull Requests.'
    default: 'false'
  ALLOW-FORCE-PUSHES:
    description: 'Set to true if you want to permit force pushes for all users with push access.'
    default: 'false'
  ALLOW-DELETIONS:
    description: 'Set to true if you want to allow users with push access to delete matching branches.'
    default: 'false'
  INCLUDE-ADMINISTRATORS:
    description: 'Set to true if you want to enforce all configured restrictions for administrators, as well.'
    default: 'false'
  RESTRICTIONS-USERS:
    description: 'List of users allowed to push on the protected branch.'
    default: ''
  RESTRICTIONS-TEAMS:
    description: 'List of teams allowed to push on the protected branch.'
    default: ''
  RESTRICTIONS-APPS:
    description: 'List of apps allowed to push on the protected branch.'
    default: ''
    
runs:
  using: 'node16'
  main: 'dist/index.js'
