name: BP
on: 
  push:
    branches:
       -main
jobs:
  BP:
    runs-on: ubuntu-latest
    steps:
      - name: Run Branch Protection
        uses: venh/branch-protection@v1.1.0
        with:
          token: '${{ secrets.token }}' 
          org: ManojKumar2133 
          rulesPath: ./rules.json 
          includedReposPath: ./includedRepos.txt
          # excludedReposPath: ./excludedRepos.txt
          action: set
