name: Build Job
on: [workflow_call,workflow_dispatch]
   
jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: ManojKumar2133/github-actions-course-resources/Code/"02 Basics"/"02 Starting Project"/.github/workflows@main
        
       
